- name: Debian. nginx. install package
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Debian. nginx. enable and start servce
  service:
    name: nginx
    state: started
    enabled: yes

- name: Debian. nginx. deploy 
  vars:
    virtual_hosts: "{{ ubuntu_virtual_hosts }}"
    conf_dir: "{{ nginx_conf_dir }}"
    html_dir: "{{ ubuntu_home }}"
  include_tasks: deploy.yaml
  with_items: "{{ virtual_hosts }}"

- name: Debian. nginx. restart
  service:
    name: nginx
    state: restarted

- name: Debian. nginx. check virtualhosts
  vars:
    virtual_hosts: "{{ ubuntu_virtual_hosts }}"
  include_tasks: check.yaml
  with_items: "{{ virtual_hosts }}"
