name: Docker Image CI

on:
  push:
    branches: 
    - gimain

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSW}}
      run: |
        winpty docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag alexeyby/bottle:$(date +%s)
      
    - name: Docker Push
      run: docker push alexeyby/it-a
