name: Docker Image CI

on:
  push:
    branches: 
    - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag alexeyby/bottle:$(date +%s)
    
      - name: Docker Push
        run: docker push alexeyby/it-a
