name: Docker CI

on:
  push:
    branches: 
    - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      #-
      #  name: Build and push
      #  uses: docker/build-push-action@v3
      #  with:
      #    push: true
      #    context: .
      #    tags: alexeby/it-a/docker:latest
      - name: Build the Docker image # push The image to the docker hub
        run: docker build . --file Dockerfile --tag $DOCKER_USER/$REPO_NAME:${{ steps.date.outputs.date }}
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USER }}/it-a:${{ steps.date.outputs.date }}