name: Docker CI

on:
  push:
    branches: 
    - main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./09.Docker/Dockerfile
          tags: alexeyby/docker:latest