name: Validate manifests

on: [push, pull_request]

jobs:
  look_for_manifest:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ env.files }}
    steps:
      - name: Get manifests
        uses: actions/checkout@v2
        id: files
      - run: echo "::set-output name=matrix::$(ls manifests/*.yaml | jq -R -s -c 'split("\n")[:-1]')" 
  validate_manifest:
    needs: look_for_manifest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-files: ${{fromJson(needs.look_for_manifest.outputs.files)}}
      fail-fast: false
    steps:
    - uses: actions/checkout@v2 
    - name: Test with kubeval
      uses: instrumenta/kubeval-action@master
      with: 
       files: ${{matrix.k8s-files}}

  send_notification:
    needs: validate_manifest
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: '#builds'
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: 'Kubeval validatuion - Completed!'
        SLACK_USERNAME: GitHub
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
